### ISSUE TITLE
faire MCD

### ISSUE THREAD

**Issue by j314h** [nsevendev/hephaistos#2]
je mets un ticket, pour marqué un point de terminaison quand le MCD sera fini (et du coup j'ai mis en cours)

**Comment by j314h** [comment]
@Aurelien0192 j'ai fais le MCD au final hahahaha
si tu peux jeter un oeil si c'est OK pour toi que tu vois pas des truc en plus ou autre
commente ce ticket et si jamais c'est OK creer une MR de la branch MCD sur la branch main ;-) je la validerai

**Comment by j314h** [comment]
@BoissonMathis 
ton MCD il est où ? tu as utilise drawio sur le navigateur relier au repository back et dans un dossier documentation ? je sais plus si c'est toi qui doit faire ou moi 

le top c'est de faire une branch MCD creer un dossier documentation et de relier le schema drawio depuis le navigateur avec

**Comment by BoissonMathis** [comment]
Si tu parle du début de mcd que j'ai fait, il est sur mon drive et je te l'ai partagé ma semaine dernière. Pour le schéma, il est relié à la branch mathis dans un dossier schéma
